### ISSUE TITLE
Re-add component(1) support

### ISSUE THREAD

**Issue by eriwen** [stacktracejs/stacktrace.js#101]
Temporarily took this out. Don't forget to add back in before 1.0 release.

**Comment by oliversalzburg** [comment]
@eriwen I have no experience with component. What was the problem that made you decide to remove the `component.json`?

**Comment by oliversalzburg** [comment]
I pushed `component.json` files into all repos. I hope I was doing it right, because I have no experience with component at all.

@ronkorving Could you take a look at the files?

**Comment by ronkorving** [comment]
For starters, your tags have to match your versions. Prefix v's and everything.
Second, your dependency versions have to match with their tag-names and are best left exact (not semver ranges), to be more compatible with older versions of component (I know we still deal with that in production).

You can test if it works by running:

```sh
npm install -g component
component install stacktracejs/stacktrace.js
```

Then looking at the `./components` folder it creates. It should contain every component, including all dependencies.

**Comment by oliversalzburg** [comment]
@ronkorving Cool. Thanks for your help. 

I had noticed that `component install` didn't pull in the dependencies. I assumed that's because component only looks for tags, but doesn't really use the `component.json` that's in master.

I'll have another look at it shortly.

**Comment by ronkorving** [comment]
Thanks :)

**Comment by oliversalzburg** [comment]
Alright. The `v` prefix was only used on the main project. I pushed an additional tag for 0.6.4 (without `v` prefix) for the time being. Hopefully, @eriwen agrees that future releases should just be published without the prefix as well.

I also removed the semver ranges from the dependencies.

`component install stacktracejs/stacktrace.js` still only downloads stacktrace.js itself. I'm assuming that's because component will retrieve the `component.json` for the latest tag (v0.6.4), but the new `component.json` was only just added to master.

I hope this will resolve itself, once 1.0 is released.

**Comment by eriwen** [comment]
Looks like this is going to be a bit tricky because we can't depend on `mozilla/source-map` directly (it doesn't have a `component.json` file. I think we'll have to distribute a bundled stacktrace-gps with source-map as a component to get around this.

**Comment by ronkorving** [comment]
Honestly, I'm starting to regret my request for component support at this point. I don't really want you guys to jump through crazy hoops to support a virtually dead technology to be honest.

**Comment by eriwen** [comment]
If our users are using it, better to support it. I don't think it'll be tough to do what I suggested, but if it is then we can consider pulling `component(1)` support until we have more demand.

**Comment by ronkorving** [comment]
I think I was the most vocal requester, not sure how many others are left. I wouldn't use component on any new project today, but I have some apps to maintain that use it and stacktracejs.

**Comment by eriwen** [comment]
Should be all fixed now. Please let us know if anything is missing.
