### ISSUE TITLE
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience

### ISSUE THREAD

**Issue by cowwoc** [stacktracejs/stacktrace.js#107]
Version 0.6.4

Chrome 40.0.2214.111 now gives a warning every time stacktrace.js is loaded: "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/." (caused by line 373)

This is reproducible 100% of the time.

**Comment by eriwen** [comment]
@cowwoc Thanks for the heads up.

I'm likely not going to fix this in v0.x because it requires somewhat fundamental changes to the API.
v1.x makes async requests, so this won't be problem.

I hope you'll consider trying v1.0 now or very soon. I'd love your feedback.

**Comment by cowwoc** [comment]
@eriwen I was actually going to close this issue. Something was screwy in my machine state. After a clean-build cycle I could no longer reproduce this issue.

Re: v1.0, is the updated documentation and migration guide up?

**Comment by eriwen** [comment]
Glad to hear it. 

Re: v1.0, non-thorough API/Usage in the README on master. Migration guide pending. I'm sure you're aware that it's not released yet, but what's there is almost ready.
