### ISSUE TITLE
Null object at IE9 when loading page 

### ISSUE THREAD

**Issue by jpcofr** [stacktracejs/stacktrace.js#109]
I've added the library to a page by adding the script from the CDN. When it finishes loading, at IE9, the following null exception occurs:

SCRIPT5007: Unable to get value of the property 'polyfill': object is null or undefined 
stacktrace.js, line 12 character 5

**Comment by eriwen** [comment]
@jpcofr To be clear this is the cdnJS CDN, correct? 

It sounds like they may have the 1.0 version of StackTrace JS marked as 0.6.4

**Comment by jpcofr** [comment]
@eriwen yes, that is right, http://cdnjs.com/libraries/stacktrace.js/

**Comment by oliversalzburg** [comment]
Seems like this is fixed: https://cdnjs.cloudflare.com/ajax/libs/stacktrace.js/0.6.4/stacktrace.js
