### ISSUE TITLE
Latest release on npm/bower

### ISSUE THREAD

**Issue by niemyjski** [stacktracejs/stacktrace.js#115]
When will the latest code drop on bower/npm?

**Comment by eriwen** [comment]
There are a few issues to address before 1.0 hits. I'm afraid that I can't do any more work on this project until I get approval from my company. 


In the meantime, if anyone is able to submit patches for any issue under the organization for milestone 1.0, that would greatly reduce the time to release.

**Comment by niemyjski** [comment]
What kind of issues are there? Can you please elaborate? I was wanting to use 1.0 for our client https://github.com/exceptionless/Exceptionless
Is your company no longer supporting this project? Will there be someone to help maintain it?
Sent from Outlook




On Fri, Apr 17, 2015 at 7:51 AM -0700, "Eric Wendelin" <notifications@github.com> wrote:










There are a few issues to address before 1.0 hits. I'm afraid that I can't do any more work on this project until I get approval from my company. 





In the meantime, if anyone is able to submit patches for any issue under the organization for milestone 1.0, that would greatly reduce the time to release.



On Thu, Apr 16, 2015 at 4:37 PM, Blake Niemyjski <notifications@github.com>

wrote:

**Comment by niemyjski** [comment]
Are source maps working?

**Comment by eriwen** [comment]
Simple source maps use cases are supported at this point. However, inline and multi-level source maps are not. See https://github.com/stacktracejs/stacktrace-gps/issues

**Comment by niemyjski** [comment]
Thanks for the heads up. Is there anything blocking that I should be worried about going with and using 1.0? I'll be more than happy to fix any bugs I come across but I want to know that I'm not investing time in something that doesn't work after I get it integrated.

**Comment by eriwen** [comment]
I'm not aware of any blockers. There may be some yet undiscovered edge-case
bugs, however I believe the core and dependencies are well tested. I
encourage you to check out the testing to convince yourself.

My personal email is on my GitHub profile if you have questions not used
for the issues page.

-Eric

**Comment by niemyjski** [comment]
Thanks, I'm going to push ahead and use your library :). I wish there was a 1.0 alpha release so I could pull that down instead of doing a manual source import.

**Comment by niemyjski** [comment]
If you could push one that would be a huge help to myself and others as setting up takes a lot to make sure I have everything imported.

**Comment by niemyjski** [comment]
I was able to get it using this:

```javascript
npm install git://github.com/stacktracejs/stacktrace.js.git --save-dev
```

**Comment by eriwen** [comment]
We have a workaround until 1.0 is published because from here on we intend to maintain forward compatibility with 1.x
