### ISSUE TITLE
Dependency on ES6-Promises

### ISSUE THREAD

**Issue by niemyjski** [stacktracejs/stacktrace.js#116]
I don't think there should be any polyfills or calls to polyfill calls for es6 promises in the code. This kind of goes against what a polyfill is (if it doesn't exist add it, not require it all the time). We are already using es6-shim and now have a second dependency for the same thing. I could see bringing it in for test setup but that's it, leave it up to the end user.

**Comment by niemyjski** [comment]
Can we please make this change? I'd be more than happy to do the pull request for this.

**Comment by eriwen** [comment]
I'd be willing to consider an implementation that only requires ES6 Promise if promises aren't already supported (via shim or native). Note that the library covers more than the current spec, so we have to be careful to avoid incompatible promise implementations.

**Comment by niemyjski** [comment]
Considering most modern browsers support it or will really soon. I think we should be using the standard shim library that everyone should have installed.

We've GOT to trim the fat.. I just realized that my lib with an external dependency on:

*  'node_modules/es6-promise/dist/es6-promise.js',
*  'node_modules/stackframe/dist/stackframe.js',
*  'node_modules/error-stack-parser/dist/error-stack-parser.js',
*  'node_modules/stack-generator/dist/stack-generator.js',
*  'node_modules/stacktrace-gps/dist/stacktrace-gps.js',
*  'node_modules/stacktrace-js/dist/stacktrace.js'

comes out to 36KB.. That's really dang large just to parse a stack trace with source maps.

**Comment by niemyjski** [comment]
Is there anything I can do to help rip the es6 promise dependency out and just use es6 promises (either supported by the browser or any shim http://caniuse.com/#feat=promises). If we are calling anything not in the es6 promises spec we should be putting it on the prototype.

**Comment by eriwen** [comment]
I understand that you want to keep the library slim because you already have a shim, but I am intentionally adding/keeping the dependency so that stacktrace.js works in *all* major browsers without extra effort.

If you feel strongly about this, I recommend you maintain a trimmed-down fork.

**Comment by niemyjski** [comment]
People who use this library are developers who understand dependencies.. You are taking a hard dependency on a library that may not be needed and doesn't adhere to the spec. Also, your minified builds don't include it... Not only that but many people already have this library or another promise polyfill library and now you are duplicating 18KB.

I'd be more than happy to do all the work including updating the readme. I don't have the time to maintain a fork long term. Regardless this is a blocking issue for many people including me. I want to release an es6 version of my library that doesn't have this polyfil and now I can't.. Which brings me to my next point. Why should I put this file size burden on all my users, when I could use a different library that doesn't force this.

**Comment by niemyjski** [comment]
It's not your responsibility to ensure your library doesn't work if a developer chooses not to use your polyfill of choice. Maybe he doesn't even need a polyfill if he can guarantee his app is using the latest internally.

**Comment by PhilSwn** [comment]
Yeah, I'd second removing the polyfill.

**Comment by keyvan** [comment]
At the very least, by principle you have to put this on vote to people can vote.

**Comment by tekmaven** [comment]
+1

**Comment by niemyjski** [comment]
Upon further looking into this forking really isn't an option as you have 5 different repos that would need to be forked and synced..

**Comment by eriwen** [comment]
Ok, I'll consider a PR that removes es6 promise. Please refer to the contributing guide before submitting.

**Comment by niemyjski** [comment]
Thanks, I'll work on getting this done shortly.

**Comment by circuitrider** [comment]
Thank you very much. Polyfill would be cruft in my solution and I appreciate your work.

**Comment by oliversalzburg** [comment]
This has been fixed in master and will land in the next release.
