### ISSUE TITLE
Get stack trace from window.onerror.

### ISSUE THREAD

**Issue by niemyjski** [stacktracejs/stacktrace.js#117]
It seems that tracekit automatically wires up to the window.onerror and gives you the stack trace in a callback (https://github.com/occ/TraceKit/blob/master/tracekit.js#L159). Can we do the same thing?

It seems like their implementation doesn't cover everything. This article looks like it covers everything you'd need to know: https://danlimerick.wordpress.com/2014/01/18/how-to-catch-javascript-errors-with-window-onerror-even-on-chrome-and-firefox/

**Comment by niemyjski** [comment]
Seems to be a well known issue still: http://blog.errorception.com/2013/10/stack-traces-windowonerror-and-future.html

**Comment by eriwen** [comment]
This is documented in the [/stacktracejs/stacktrace.js/README.md](README). May consider this in the future if we can make it 100% reliable and useful.
