### ISSUE TITLE
Node Support

### ISSUE THREAD

**Issue by niemyjski** [stacktracejs/stacktrace.js#118]
I know that you recommended using this:https://www.npmjs.com/package/stack-trace however, I was wondering if this library will also work for node? Is there anything that won't work?

**Comment by eriwen** [comment]
Fetching sources in stacktrace-gps would have to be handled in a node specific way. Anything referencing window (eg window.onerror) would have to be defensive. 

Other than that, it should work.

**Comment by niemyjski** [comment]
Would you even need to fetch sources for a node app? I'm not a node developer but I can't think of any reason why you'd want to uglify it can you?  Maybe for external libs?

**Comment by eriwen** [comment]
Well you have to fetch source map files, at least.

**Comment by niemyjski** [comment]
@eriwen node18 supports fetch now, perhaps this changes support for this.
