### ISSUE TITLE
Node require issues with single file

### ISSUE THREAD

**Issue by niemyjski** [stacktracejs/stacktrace.js#119]
I need to distribute my app externally using a single file by concatting all of my dependencies: https://github.com/exceptionless/Exceptionless.JavaScript/blob/master/dist/exceptionless.es5.js

This works great for web, however when I went to create my node sample I ran into a bunch of issues when my require statement was hit: https://github.com/exceptionless/Exceptionless.JavaScript/blob/master/example/express/app.js#L4

```
Error: Cannot find module 'source-map/lib/source-map/source-map-consumer'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at c:\Code\Exceptionless.JavaScript\dist\exceptionless.es5.js:1237:34
    at Object.<anonymous> (c:\Code\Exceptionless.JavaScript\dist\exceptionless.es5.js:1241:2)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```
Do you have a recommended way to get around this issue? I'm new to node but I wanted to have a single file with all my dependencies.

**Comment by niemyjski** [comment]
If I change:

```javascript
module.exports = factory(require('source-map/lib/source-map/source-map-consumer'), require('es6-promise'), require('stackframe'));
```
To:
```javascript
module.exports = factory(null, require('es6-promise'), require('stackframe'));
```

It works. I think this could because I didn't know source-map-consumer is a dependency. From the looks of it that file is a node module and I didn't see it references from anywhere. It doesn't have a umd spec, and doesn't look like it would play nicely bringing it in. Recommendations?

**Comment by niemyjski** [comment]
I think the dist builds should contain all external dependencies. This would save what it needs to take to bring it into your web app.

**Comment by niemyjski** [comment]
I brought in the library as a test and had a ton of issues and even tried a few things. @eriwen  Do you have any recommendations on getting this working? I'm at a loss.

**Comment by eriwen** [comment]
Agreed that dist/ should contain a file with all dependencies.

**Comment by eriwen** [comment]
`dist/stacktrace.min.js` now includes all dependencies (and no polyfills)
