### ISSUE TITLE
Not as advertised....

### ISSUE THREAD

**Issue by dvandusen** [stacktracejs/stacktrace.js#123]
This appears to be a great tool, except that it is difficult to get started on.
It may because of the dependencies on polyfills or something, but just using the test from stacktracejs.com fails....  

        <!DOCTYPE html>
        <html>
        <head lang="en">
            <meta charset="UTF-8">
            <title></title>
        </head>
        <body>
        <script type="text/javascript" src="https://rawgithub.com/stacktracejs/stacktrace.js/master/stacktrace.js"></script>
        <script type="text/javascript">
            // your code...
            var trace = printStackTrace();
            alert(trace.join('\n\n')); // Output however you want!
            // more code of yours...
        </script>
        
        </body>
        </html>

results in:
            Uncaught TypeError: Cannot read property 'polyfill' of undefined
            StackTrace
            (anonymous function)
            (anonymous function)

I saw the long list of dependencies and wonder if they are really required on the simple example test given.

Thanks for this - to all the guys working on it!

**Comment by eriwen** [comment]
I'm sorry you had a bad experience. We just need to fix the link on the site to point to the stable version until v1.0 is released. 

Also note that the only dependencies will be other parts of stacktrace.js (e.g. Error parsing or stack generation)

**Comment by dvandusen** [comment]
I really appreciate your work and response - I presume Stacktrace is 
usable, but where is the stable version?

**Comment by eriwen** [comment]
Sorry, I should clarify that I mean the stable branch at






https://github.com/stacktracejs/stacktrace.js/tree/stable?files=1 




Grab stacktrace.js from there.

**Comment by dvandusen** [comment]
Thx!

**Comment by dandv** [comment]
As of now, the rawgithub link listed at http://www.stacktracejs.com/ fails with the `Cannot read property 'polyfill' of undefined` error, but the CDN version of the library listed in the README works. Perhaps update the website?

**Comment by oliversalzburg** [comment]
@dandv A new website is already complete and will go live for the next major version of the library.

**Comment by erezcohen** [comment]
Problem is, the documentation at https://github.com/stacktracejs/stacktrace.js is already updated to the new version, however doing "bower install stacktrace-js" installs the old/stable version. One has to dig into the source to realize there's no such thing as ```StackTrace.get()``` and that ```printStackTrace()``` needs to be used instead...

**Comment by eriwen** [comment]
Website and project are now polarized!
