### ISSUE TITLE
damage link on wiki - Upgrading? Check the 0.x -> 1.x Migration Guide

### ISSUE THREAD

**Issue by cybermerlin** [stacktracejs/stacktrace.js#126]
on page
https://github.com/stacktracejs/stacktrace.js
damage link on wiki - ```Upgrading? Check the 0.x -> 1.x Migration Guide```

And help me please, I was code:
```javascript
var _Error = function(e){
		var msg = isString(e)? e : '';
		if(!isDefined('printStackTrace',true)) load_js('js/stacktrace.js')

		e= (!!msg? new Error(msg) : (e||new Error()));
		/**
		 *    @cfg {Number} [code=0]
		 */
		e.code = (e.code||e.number||0);
		/**
		 *    @cfg {String} [message]
		 */
		e.message = (e.message||'');
		/**
		 *    @cfg {String} [userMsg]
		 */
		e.userMsg = (e.userMsg||msg); // (e.userMsg? e.userMsg : e.message);
		/**
		 *    @cfg {String} [file]
		 */
		e.file = e.file || '';
		/**
		 *    @cfg {Number} [line=0]
		 */
		e.line = e.line || 0;
		/**
		 *    @cfg {String} [function]
		 */
		e['function'] = (e['function'] || '');
		/**
		 *    @cfg {String} [stack]
		 */
		e.stack = (e.stack || '');

		if(!e['function'] && isDefined('printStackTrace',true)){
			var stack = (printStackTrace() || [])
					,_target = stack[stack.indexOfPart('printStackTrace')+2]
					;
			if(_target){
				var match_forLine = _target.match(/:(\d)*:(\d)*$/);
				e.line = (e.line || (match_forLine && match_forLine.length? match_forLine[1] : 0));
				e.stack = (e.stack || JSON.encode(stack));
				e['function'] = (e['function'] || _target.replace(/@.*$/,'') || '');
			}
		}

		return e;
	};
```

how can I get stack now?

**Comment by eriwen** [comment]
Ah, sorry about that. 

You can find the very same [Migration Guide](https://github.com/stacktracejs/stacktrace.js/blob/master/MIGRATION_GUIDE.md) in the repo.

**Comment by cybermerlin** [comment]
thanks.
but...
help me to understand for getting "stack" from last error if not have a Error, for example my sample in first post... earlier I just run printStackTrace() and has recieved the Error with stack trace (even if the browser not include stack trace in to Error)

**Comment by eriwen** [comment]
@cybermerlin There are 2 ways you can handle this with v1.0.

The async way - Pass a `callback` function to `_Error` and use `StackTrace.get().then(callback)` wherever you were calling `printStackTrace()`. Note that `stacktrace.js` filters the stack for you and the stack is now a [StackFrame](https://github.com/stacktracejs/stackframe) object. 

The synchronous way - Use [error-stack-parser](https://github.com/stacktracejs/error-stack-parser) to parse `e` given that you provide a default Error(). `ErrorStackParser.parse(e)`. Note that this does not take advantage of source maps.

**Comment by eriwen** [comment]
Link fixed
