### ISSUE TITLE
Version?

### ISSUE THREAD

**Issue by cope** [stacktracejs/stacktrace.js#128]
Maybe I missed it, but whats the current version of stacktrace.js? (https://github.com/stacktracejs/stacktrace.js/blob/master/dist/stacktrace.js)

**Comment by oliversalzburg** [comment]
master is nearing the 1.0 release

**Comment by cope** [comment]
Ah, I was under the impression that 1.0 was already out. I have my own cdn (kindof) and I have the 0.6.4 folder and a 1.0 folder and the code in that one was quite different from the latest, so I assumed, wrongly obviously, that this current code is 1.x or 1.0.x

My bad.
