### ISSUE TITLE
printStackTrace is not defined

### ISSUE THREAD

**Issue by cope** [stacktracejs/stacktrace.js#129]
The example from the website (http://www.stacktracejs.com/) throws an error:
`Uncaught ReferenceError: printStackTrace is not defined`

Can you please give a simple example of usage in the browser?

I tried to understand the examples from the README, but I just don't get them :(

**Comment by oliversalzburg** [comment]
Please note that that page refers to the 0.6.4 release, not the current master.

**Comment by cope** [comment]
Ah, again my bad. I loaded 0.6.4 and then the example worked!

Thanks.
