### ISSUE TITLE
Feature: Option to disable sourcemaps resolving

### ISSUE THREAD

**Issue by auchenberg** [stacktracejs/stacktrace.js#130]
Feature request: Option to disable sourcemaps resolving, in order to minimize dependencies, as in my case I have moved the source maps resolving server-side.

**Comment by eriwen** [comment]
You can call `StackTrace.get({offline: true})` and `StackTrace.fromError(error, {offline: true})` to prevent all network requests including source-maps. 

Does this suit your need? The only thing you'd also lose is further analysis on the source-mapped source (which is minimal at this point but expected to improve if we integrate esprima)

**Comment by auchenberg** [comment]
Aha, interesting, but not exactly.

I probably need a build of stacktrace.js, that doesn't require stacktrace-gps in order to avoid the 50KB+ dependencies thats needed for sourcemaps.

**Comment by eriwen** [comment]
OK. Well if you only need to support IE10+, you can use [error-stack-parser](https://github.com/stacktracejs/error-stack-parser) like so: `ErrorStackParser.parse(new Error())` and that will give you a stack from wherever you call it. Only 1.4K min-zipped :)

If you need IE9-, it gets a bit more complicated but we can work it out.

**Comment by auchenberg** [comment]
Yeah, I ended up wrapping ```error-stack-parser ``` myself, but I'd really like to get IE8+ support. 

On that note, do you have an overview of the differences between https://github.com/csnover/TraceKit and stacktrace.js? I'm having a hard time getting the overview.

**Comment by eriwen** [comment]
IE8+ support isn't quite as difficult as I may have implied:

```
var stack;
try {
    stack = ErrorStackParser.parse(new Error());
catch (e) {
    stack = StackGenerator.backtrace();
}
```

However, note that `StackGenerator.backtrace()` doesn't work under strict-mode. You can also steal part of the logic here if you want: https://github.com/stacktracejs/stacktrace.js/blob/master/stacktrace.js#L62

As for TraceKit, I haven't looked at it recently; my general understanding of the strategy there is to hook into as many native/jquery error handlers as possible and propagate through a pub/sub API. The internals of the 2 projects are fairly similar - we unsuccessfully tried to combine the projects a couple years ago.

**Comment by eriwen** [comment]
@auchenberg Sounds like you have this worked out for now. Do you still think this is worthwhile? We're happy to provide this if you think it's useful.

**Comment by auchenberg** [comment]
@eriwen Not completely, but thanks for the clarifications and help. It's much appreciated :)
