### ISSUE TITLE
Document dependencies

### ISSUE THREAD

**Issue by orf** [stacktracejs/stacktrace.js#132]
Can you please document your browser dependencies somewhere? It seems I need to include the Mozilla source map library (https://github.com/mozilla/source-map/), but this maps to `window.sourceMap` and this library expects `window.SourceMap` and is not documented anywhere.

**Comment by eriwen** [comment]
stacktrace.min.js should include all dependencies - perhaps you're using vanilla stacktrace.js? 

May I know a bit more about how you're encountering this error so that I can reproduce it?

**Comment by orf** [comment]
Awesome! I was using the un-minified stacktrace.js. I've now got it to generate proper stacktraces, and I cant express how useful those will be in our project (so a big thank you!)

One problem though, it appears the library is needlessly requesting the same .map and .js files over and over again, which causes a big performance drop. Here is my network panel after generating a stacktrace:

![image](https://cloud.githubusercontent.com/assets/1027207/10424903/1449c550-70cb-11e5-92ad-0e329a0f02c5.png)

![image](https://cloud.githubusercontent.com/assets/1027207/10424956/8f3dfcae-70cb-11e5-939a-c8f8a99ba752.png)

I think it's requesting the file once per line in the stacktrace? As they are all the same file/URL shouldn't only one request be made?

**Comment by eriwen** [comment]
Glad that worked.

The library intends to use the browser cache, but it looks like that's not always working. Do you happen to have a condensed example we can test against to fix this?

**Comment by eriwen** [comment]
I've submitted https://github.com/stacktracejs/stacktrace-gps/issues/19 against stacktrace-gps for this new issue.

**Comment by orf** [comment]
Sure, I will try and replicate it and post in that issue. Thanks!
