### ISSUE TITLE
Make it clear that dist/stacktrace.js doesn't include dependencies.

### ISSUE THREAD

**Issue by eriwen** [stacktracejs/stacktrace.js#140]

**Comment by evilaliv3** [comment]
I'm dealing with this same issue:
1) it is not clear that the following dependencies defined in package.json need to be included manually by the user:

```
        "error-stack-parser": "~1.2",
        "stack-generator": "~1",
        "stacktrace-gps": "~2"
```

2) the "es6-promise" is even not included as dependency an i discovered that i was requiring to include it manually to get it working on IE (now 9, 8, 10, 11) was working cause IE does not implement promises natively (http://caniuse.com/#search=promise); i would suggest that the library clarify that to target IE the user should include it.

All these error would have been spotted automagically if a browser testing tool was implemented as i'm now suggesting on https://github.com/stacktracejs/stacktrace.js/issues/143
