### ISSUE TITLE
Preload source maps before running promise on stackframes

### ISSUE THREAD

**Issue by mgolinelli** [stacktracejs/stacktrace.js#141]
Hi,

Is it possible to preload source maps before running promises on each stackframes to avoid multiple ajax call on same resources (source map not yet in local cache) ?

Best

**Comment by eriwen** [comment]
Couple options here:

1) stacktrace.js v1.0.1 should deduplicate network requests like ones for source maps. If you are using v1.0.1 and you're seeing duplicate requests for the same source map, that's a bug we'd like your example for fixing.

2) All relevant stacktrace.js methods have a `{sourceCache: {"http://foo.com/url.js.map": "(mapsource)"}}` option you can use to pre-populate the cache.

**Comment by mgolinelli** [comment]
Dear eriwen,

In fact it works using StackTrace.fromError(error, { sourceCache : {}})
If you dont specify a sourceCache, the cache is 'rebuilt' for each stackframes:

 return function StackTraceGPS(opts) {
        if (!(this instanceof StackTraceGPS)) {
            return new StackTraceGPS(opts);
        }
        opts = opts || {};

        this.sourceCache = opts.sourceCache || {};
        this.ajax = _xdr;

        this._get = function _get(location) {
            return new Promise(function (resolve, reject) {
                var isDataUrl = location.substr(0, 5) === 'data:';
                if (this.sourceCache[location]) {
                    resolve(this.sourceCache[location]);

Best
