### ISSUE TITLE
How to print "stack trace" within window.onerror using stacktrace.js?

### ISSUE THREAD

**Issue by kiwenlau** [stacktracejs/stacktrace.js#142]
I want to use window.onerror to track uncaught error. And I want to print "stack trace" like this:

```
ReferenceError: aler is not defined
    at a (http://localhost:8080/test/test01.js:21:2)
    at b (http://localhost:8080/test/test01.js:25:3)
    at c (http://localhost:8080/test/test01.js:29:3)
    at http://localhost:8080/test/test01.js:32:1
```

How can I print it within.onerror using stacktrace.js?

Following code does't work...

**onerror.js**
```js
window.onerror = function(msg, file, line, col, error) {
    
    function callback (result) {
    	console.log(result);
    }

    function errback (error) {
    }

    StackTrace.fromError(error).then(callback).catch(errback);
};
```

For your information, following are my html and javascript file used for test.

**test.html**
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Test</title>
    <script src="stacktrace.js"></script>
    <script src="onerror.js"></script>
    <script src="test.js"></script>
</head>

<body>
    Test
</body>

</html>
```

**test.js**
```js
function a() {
	aler(hello);
}

function b() {
  a();
}

function c() {
  b();
}

c();
```

**Comment by eriwen** [comment]
Could you be more specific when you say it "doesn't work"? Does it throw an Error, do nothing, or something else? 

I notice that you are using "stacktrace.js". Perhaps you're not using "dist/stacktrace.min.js" which has dependencies bundled? That is a source of confusion we have corrected recently.

**Comment by kiwenlau** [comment]
Thank you for your reply! I modified onerror.js and got what I want...

```js
window.onerror = function(msg, file, line, col, error) {
    // callback is called with an Array[StackFrame]

    function callback(result) {
        // body...

        for (var i = 0; i < result.length; i++) {
            console.log(result[i]);
        }
    }

    function errback(error) {
        // body...
        //console.log(error);
    }


    StackTrace.get().then(callback).catch(errback);
};

```

**Comment by eriwen** [comment]
Great!

**Comment by midhun8454** [comment]
am not getting the unminified response for staxktrace.js? can anyone help me to dig out?
I have the min.error in this function and am logging this error
componentDidCatch(error, errorInfo) {log(error)//min.error}
How can i log unminified error?
