### ISSUE TITLE
Evaluate integration of Saucelabs in order to test cross-browser compatibility on commit

### ISSUE THREAD

**Issue by evilaliv3** [stacktracejs/stacktrace.js#143]
It would be valuable to integrate with Saucelabs in order to track code coverage on commit.

Given that grunt and karma are used in the project, from a rapid analysis the interesting grunt package to be used is:  https://github.com/karma-runner/karma-sauce-launcher

This way it will be possible to automatically execute all the unit test on the selection of browsers targeted by the library (all) and know proactively where it is not working.

An example of the output is the following: https://github.com/globaleaks/GlobaLeaks

**Comment by oliversalzburg** [comment]
The project is already tested using SauceLabs: https://travis-ci.org/stacktracejs/stacktrace.js

**Comment by evilaliv3** [comment]
I see oliver thanks.

it should be valuable to export the results in the readme so to have them exposed?

**Comment by oliversalzburg** [comment]
@evilaliv3 Good idea. Maybe @eriwen can take care of that, I'm still not very familiar with SauceLabs :(

**Comment by eriwen** [comment]
The TravisCI build only passes if all tests pass in all browsers configured for Sauce (in karma.conf.ci.js)

@evilaliv3 are you aware of a nice way to present the individual browser results on the README with Sauce?

**Comment by oliversalzburg** [comment]
Apparently, we could use:

[![Sauce Test Status](https://saucelabs.com/browser-matrix/stacktracejs.svg)](https://saucelabs.com/u/stacktracejs)

**Comment by evilaliv3** [comment]
exactly!

probably more version should be tested? and what about adding also android and safari under unit testing?

**Comment by oliversalzburg** [comment]
Sounds reasonable. I see that those platforms are commented in `karma.conf.ci.js`. @eriwen do you know what that is?

**Comment by eriwen** [comment]
Sometimes mobile browsers fail to start as well as older browsers. I don't think I've ever gotten IE6 to load on Sauce. 

Another is that for some reason mocking Ajax requests on old IEs is difficult with Jasmine 1.x, and I've never gotten Jasmine 2.x to do what I want.

That said, we should try to enable as many as we can get reliably working. FWIW, I manually test old IEs and such using the old functional test suite.

**Comment by eriwen** [comment]
This commit https://github.com/stacktracejs/stacktrace.js/commit/3dc10e4239b200e7f317f648b38832e89483822b from @ssenbud addresses some of this. It turns out that we'll need conditional tests for IE8 and lower because we can't polyfill JS features required by SourceMapConsumer (specifically, ES5 getters and setters).

**Comment by eriwen** [comment]
Given how flaky Sauce has been giving us old IE instances (among other things) and the fact that we do have a good spread of browsers displayed for every project, I'm inclined to call that good. 

If anyone has any objections, please speak up before March 28th.
