### ISSUE TITLE
ReferenceError: exports is not defined source-map.js:6:1

### ISSUE THREAD

**Issue by ghovmand** [stacktracejs/stacktrace.js#144]
Hi

When I install with `bower install stacktrace-js` and run my app, I get following in the console

`ReferenceError: exports is not defined source-map.js:6:1`

I use gulp to inject and serve the app which is an angular app.

Thanlks

**Comment by eriwen** [comment]
Similar to what @oliversalzburg mentioned in https://github.com/stacktracejs/stackframe/issues/7 - please include `dist/stacktrace.min.js`. This is required due to how SourceMap is written, it must be built using something like webpack and cannot be independently included.
