### ISSUE TITLE
How to get the "stack trace" string?

### ISSUE THREAD

**Issue by kiwenlau** [stacktracejs/stacktrace.js#147]
I'm trying to **get the "stacktrace" string and return it** other than **log it in the console**. However, following code doesn't work...
```
    function getStacktrace() {

        var stringifiedStack;
        var callback = function(stackframes) {
            stringifiedStack = stackframes.map(function(sf) {
                return sf.toString();
            }).join('\n');
            //console.log(stringifiedStack);
        };

        var errback = function(err) {
            console.log(err.message);
        };

        StackTrace.get().then(callback).catch(errback);

        //console.log(stringifiedStack);
        return stringifiedStack;
    }
```

**Comment by oliversalzburg** [comment]
What do you mean when you say it doesn't work? 

Also, there's a mistake in your `errback` function; an extra `;` in `console`.

**Comment by kiwenlau** [comment]
@oliversalzburg Thank you.
*console.log(stringifiedStack)*before*return stringifiedStack;*just print *undefined*

**Comment by eriwen** [comment]
@kiwenlau The reason `stringifiedStack` is `undefined` when you return it is because `StackTrace.get()` runs asynchronously, so `callback()` has not been called yet.

You'll see that if you comment `console.log(stringifiedStack);` back in _in both places_, you'll see `undefined` and then the stacktrace.

**Comment by kiwenlau** [comment]
@eriwen Thank you!
Yes, it happens as you said.
```
undefined
a()@http://localhost:8080/test/test03.js:21:14
b()@http://localhost:8080/test/test03.js:25:5
c()@http://localhost:8080/test/test03.js:29:5
{anonymous}()@http://localhost:8080/test/test03.js:32:1
```

**Comment by kiwenlau** [comment]
The problems is how can I get the stacktrace string from callback()?

**Comment by eriwen** [comment]
Well, you have gotten the stacktrace and printed it to the console, already :)

Consider what you want to do with the stacktrace when you get it. Do you want to display it on the screen, or call a function with it? I'm afraid returning it won't be very useful, you'll need to call another function to do what you want. 

Does that help?

**Comment by kiwenlau** [comment]
@eriwen I don't need to log it and I need to return it. And I don't know how to accomplish it...Thank you!

**Comment by eriwen** [comment]
I suggest you consider what you're doing with the stack after you've "returned" it. Note that it's not possible to be `return`ed with the keyword. The asynchronous nature here dictates that you must provide a callback and that is the only way to "return" the stack trace. 

`callback` does not have to be defined inline. It can be defined anywhere. You could pass the callback function to `getStacktrace`:

```js
    function getStacktrace(callback) {
        var errback = function(err) {
            console.log(err.message);
        };

        StackTrace.get().then(callback).catch(errback);
    }


        var callback = function(stackframes) {
            var stack = stackframes.map(function(sf) {
                return sf.toString();
            }).join('\n');
            // Do something with stack here
        };
```

**Comment by kiwenlau** [comment]
@eriwen This is not I want. Thank you anyway! It seems to be impossible to return stacktrace string.

**Comment by bjentsch** [comment]
What about [`StackTrace.getSync`](https://github.com/stacktracejs/stacktrace.js#stacktracegetsyncoptional-options--arraystackframe)...?

**Comment by niftylettuce** [comment]
I think what he is asking is to get a stringified stack trace into a format that is similar to `err.stack`.  Calling `stackframes.map(sf => sf.toString()).join('\n')` does not yield the same format as `new Error('foobar').stack`.

**Comment by niftylettuce** [comment]
e.g. be able to pass stack frames to prepareStackTrace : <https://github.com/nodejs/node/blob/6ce87c027dc2a16e1b8d85c753b52270ae0c6054/lib/internal/errors.js#L22-L44>

**Comment by niftylettuce** [comment]
The `toString` PR has been submitted <https://github.com/stacktracejs/stackframe/pull/23>.
