### ISSUE TITLE
stacktracejs creates new GPS instance for every fromError

### ISSUE THREAD

**Issue by scamden** [stacktracejs/stacktrace.js#148]
Because the sourceCache for stacktrace-gps is stored on the instance this causes sources to be refetched for every stackframe. Any chance we could somehow use a single instance of GPS so these files are cached? otherwise i'm not sure of the use of the GPS source cache.. maybe i'm missing something

for reference: 
``` javascript
fromError: function StackTrace$$fromError(error, opts) {
            opts = _merge(_options, opts);
            return new Promise(function (resolve) {
                var stackframes = ErrorStackParser.parse(error);
                if (typeof opts.filter === 'function') {
                    stackframes = stackframes.filter(opts.filter);
                }
                resolve(Promise.all(stackframes.map(function (sf) {
                    return new Promise(function (resolve) {
                        function resolveOriginal(_) {
                            resolve(sf);
                        }

                        new StackTraceGPS(opts).pinpoint(sf)
                            .then(resolve, resolveOriginal)['catch'](resolveOriginal);
                    });
                })));
            }.bind(this));
        },
```

**Comment by scamden** [comment]
@eriwen thoughts on this guy?

**Comment by eriwen** [comment]
The original intent here was that we would be able to leverage the browser cache, but then allow users to override that cache (and offline mode). If we're not properly using the browser cache, that is a bug. If that is what you're seeing, could you provide a concrete example that might help us debug?

We could allow users to provide their own instance of `StackTraceGPS` which would be used instead of creating a new instance every time. I just want to make sure we solve the root problem instead of patching around it.

**Comment by scamden** [comment]
so i am seeing it not returning from cache in the browser, i'll dig a little further to make sure it's not something on our end. that said it would be cool to have th option to use our own gps instance especially to ensure the cache

**Comment by scamden** [comment]
soooooooo sorry about this. i actually had disable cache checked in chrome's dev tools.. it does appear the browser cache is working. i feel sheepish. it still might be worth allowing a single GPS instance in case we did want offline or the like. up to you on that but my hair on fire bug is solved :)

**Comment by eriwen** [comment]
No worries, I've done the same thing. 

I think providing a `gps` option is fairly easy implement and test, so it's a great way for someone to contribute. I'm going to leave this open with the hope that someone out there is motivated :)

**Comment by scamden** [comment]
Right on, I'll take a whack at it next week :)
Sterling Camden

Sent from RelateIQ

On January 6, 2016 at 8:03 PMEric Wendelin<notifications@github.com> wrote:

No worries, I've done the same thing.

I think providing a gps option is fairly easy implement and test, so it's a
great way for someone to contribute. I'm going to leave this open with the
hope that someone out there is motivated :)

—
Reply to this email directly or view it on GitHub
<https://github.com/stacktracejs/stacktrace.js/issues/148#issuecomment-169542256>
.

**Comment by scamden** [comment]
this could work: https://github.com/stacktracejs/stacktrace.js/pull/150

**Comment by kallaspriit** [comment]
Bumped into this one as well. The solution for me was to provide the same initially empty sourceCache object to calls of StackTrace.fromError so the GPS would automatically populate it and not have to fetch the same file multiple times for each stack frame and also for consecutive calls to fromError.

```javascript
const stacktraceSourceCache = {};

window.onerror = (message, filename, line, col, error) => {

	// make it always use the same source cache map to avoid fetching the same file multiple times
	const options = {
		sourceCache: stacktraceSourceCache
	};

	// attempt to resolve real error source and stack
	StackTrace.fromError(error, options).then(([...stack]) => {
		// do something with the stack
	});
}
```

Perhaps the documentation could be improved to include this tip

**Comment by scamden** [comment]
@eriwen i guess given this we could probably just close my pr eh? unless you still see some value there

**Comment by eriwen** [comment]
@scamden Yeah, I think we can close it. I really appreciate your willingness to contribute code.

@kallaspriit Thanks for the tip. We'll make sure to get this added to the docs.

**Comment by scamden** [comment]
Happy to :)
Sterling Camden

Sent from RelateIQ

On January 25, 2016 at 8:26 PMEric Wendelin<notifications@github.com> wrote:

@scamden <https://github.com/scamden> Yeah, I think we can close it. I
really appreciate your willingness to contribute code.

@kallaspriit <https://github.com/kallaspriit> Thanks for the tip. We'll
make sure to get this added to the docs.

—
Reply to this email directly or view it on GitHub
<https://github.com/stacktracejs/stacktrace.js/issues/148#issuecomment-174816656>
.
