### ISSUE TITLE
Integration with ExtJs / Sencha Cmd not working

### ISSUE THREAD

**Issue by Psychokrameur** [stacktracejs/stacktrace.js#153]
Hello,

I'm trying to integrate StrackTrace.js with ExtJs (https://www.sencha.com) and... it's not working.

My test case is the following:
- Build a standard ExtJs app (see docs here https://docs.sencha.com/cmd/6.x/touch/cmd_app.html, when Sencha Cmd is installed, you can only do the part "Creating a New Application")
- Modify app.json to add the reference to StackTrace.js

```
"js": [
        {
            "path": "https://cdnjs.cloudflare.com/ajax/libs/stacktrace.js/1.0.3/stacktrace.min.js",
            "remote": true
        },
        {
            "path": "app.js",
            "bundle": true
        }
    ],
```
- In your terminal go to your app folder and launch `sencha app watch`
- In your navigator go to http://localhost:1841/path/to/your/app
- In your web developper tools launch the first basic StackTrace test from this page https://www.stacktracejs.com/#!/docs/stacktrace-js

In the network tab, I see this result:

```
stacktrace.min.js   200 xhr stacktrace-gps.min.js:1 8.3 KB    26 ms 
%3Canonymous%3E 404 xhr stacktrace-gps.min.js:1 1.6 KB    8 ms  
%3Canonymous%3E 404 xhr stacktrace-gps.min.js:1 1.6 KB    9 ms  
%3Canonymous%3E 404 xhr stacktrace-gps.min.js:1 1.6 KB    10 ms 
%3Canonymous%3E 404 xhr stacktrace-gps.min.js:1 1.6 KB    11 ms 
stacktrace.min.js.map   200 xhr stacktrace-gps.min.js:1 0 B   479 ms    
```

With `XMLHttpRequest cannot load https://cdnjs.cloudflare.com/ajax/libs/stacktrace.js/1.0.3/stacktrace.min.js.map. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:1841' is therefore not allowed access.` error in the log console.

So, 6 network requests to small files... the impact is very small. 
But in production, this will cause 6 request to the main app.js javascript file which might be multiple MegaBytes.

I follow suggestion to put "offline:true", which seems to work better but throw 5 uncatch exception...
Which is not very satisfying...

Thanks in advance if you have some info/tips to integrate StackTrace in a better way.

(Reference to strackoverflow question: http://stackoverflow.com/questions/34950298/extjs-and-stacktrace-js/35007547?noredirect=1#comment57829509_35007547)

**Comment by eriwen** [comment]
Thank you for the thorough issue. I have reproduced the behavior you describe. 

When running StackTrace through the browser console, the file name of many stack entries will be `<anonymous>`. We have an issue filed to avoid this: https://github.com/stacktracejs/stacktrace-gps/issues/32 - once solved those 404s will go away. 

The error caused by a lack of CORS headers from CloudFlare really requires one to either filter out stackframes that include stacktrace.js itself or bundling stacktrace.min.js and stacktrace.min.js.map with your own app to avoid the need for CORS.

This would solve your immediate issue (filtering):
```
function myFilterFn(sf) { return sf.functionName !== 'Object.get' }
function callback(stackframes) { ... }
StackTrace.get({filter: myFilterFn}).then(callback);
```

**Comment by Psychokrameur** [comment]
Thans @eriwen. I'll apply your proposed patch for now and wait for the resolution of the issue mentioned.

**Comment by eriwen** [comment]
https://github.com/stacktracejs/stacktrace-gps/issues/32 was fixed some time ago. Please reopen this issue if the problem persists with stacktrace.js 1.3.6 or later
