### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by arshtepe** [stacktracejs/stacktrace.js#156]
You have in "Readme":
> Chrome 1+
> Firefox 3+
> Safari 5+
> Opera 9+
> IE 6+
> iOS 7+
> Android 4.0+

but you use Promises, promises supported by this browsers http://caniuse.com/#feat=promises .
You can use this polyfill https://github.com/zloirock/core-js#ecmascript-6-promise

**Comment by oliversalzburg** [comment]
It comes with a polyfill for browsers that don't support promises.

**Comment by simonblt** [comment]
How come I dont have the same result with Edge, FireFox versus Chrome? 
On chrome, lineNumber is like 40 under where its suppose to be. I got the right line and functioName with the other two.

Its an asp.net angularjs app and I use BundleOptimisation with Script with source map bundle.

**Comment by SeigneurPaladin** [comment]
How come i dont have right linenumber with chrome and its fine with Firefox and Edge.
Im like 40 lines under where its suppose to be with Chrome.

I use bundle optimisation and script with sourcemap.

**Comment by eriwen** [comment]
@arshtepe As Oliver pointed out, we distribute 2 versions of stacktrace.js: One with a Promises polyfill (specifically es6-promise) and one with no polyfill (for those who want a smaller library and have more modern users). I don't see any good reason to change the way this is handled.

@SeigneurPaladin Can you please file a separate issue with example code and stacktraces?
