### ISSUE TITLE
Redownloads source map and minified file

### ISSUE THREAD

**Issue by miked1090** [stacktracejs/stacktrace.js#157]
Hi, anytime I'm calling StackTrace.FromError() there is a network request to redownload the minified file AND the source map file. I am also using the newest version of stacktrace.

For now, the solution I've found is to set {offline: true } in the options, but this means the stacktrace just points to the minified file. 

I've tried setting the sourceCache to the url of the source map, 
also tried setting the sourceCache to the url of the source map and setting offline to true.
I've set sourceCache to {}, which was a suggestion I've seen a few times on here, but none of these have solved my issue.

Is there something I'm missing?

**Comment by Smolations** [comment]
:+1: for this.  It is absolutely ridiculous to have to re-download the source file and the sourcemap file for every single stack frame in the trace. Minifying is most often used in bundling operations so it should be expected that the same file/map will occur multiple times in the same trace. I understand that each individual file is needed, but they should be cached until there is a page refresh or _at least_ for each frame in the same trace. The current flow is extremely inefficient for larger bundles.

**Comment by eriwen** [comment]
Acknowledged. We should do a much better job caching requests and responses by default.

**Comment by zachlowry** [comment]
:+1: for this, it's preventing us from using stacktrace.js currently.

**Comment by Smolations** [comment]
@eriwen A quick bit of research yielded a package that could be integrated with stacktrace-gps to help solve this problem:  https://github.com/kapouer/cache-debounce
