### ISSUE TITLE
Missing changelog for version from 1.0.0 up to 1.1.0

### ISSUE THREAD

**Issue by evilaliv3** [stacktracejs/stacktrace.js#160]
Halo! you are forgetting to write the changelog for versions from 1.0.0 up to 1.1.0! :)

is there some breaking change we should care about?

**Comment by eriwen** [comment]
Thanks for the reminder. v1.1.0 was *just* published to npm - here are the changes: https://github.com/stacktracejs/stacktrace.js/commit/6dfe51fd3f4449cdb5d91f226d875abba4542e3e
