### ISSUE TITLE
Is there an example of a synchronous version of the new stack trace?

### ISSUE THREAD

**Issue by dtracers** [stacktracejs/stacktrace.js#165]
I really like the features the new one comes with but I am very dependent on it being synchronous and currently it seems like it is async.

Is a simple example of it being sync not async?

Also when using requirejs it won't work unless I create a source-map.min.js in the top level of every project I use the new version.  Is there a way to use it without adding source-map.min.js?

**Comment by benjamingr** [comment]
Answered in http://stackoverflow.com/questions/37646228/make-the-new-stackjs-library-synchrnous

**Comment by dtracers** [comment]
I was wondering if there was a to add back the synchronous version of the library so that I could just get the dumb stack trace that I then replace with the much more detailed stack trace.

I actually use exceptions like in java and so there will be some times where the exception can't really wait around for a trace to be grabbed bc you can't really tell the try catch to wait till all the promises are resolved and with deeply nested exceptions.  (some mine some not mine) it is hard to bubble up the waiting of promises for display to the user.

**Comment by eriwen** [comment]
Wish granted! v1.3.0 adds `StackTrace.getSync()`. Note that it does not support source maps or do anonymous function guessing.

**Comment by dtracers** [comment]
This is awesome! Thank you very much!

Now I can have it do the dumb one then asynchronous replace with the smart one!

Thank you! You guys are amazing!

**Comment by eriwen** [comment]
@dtracers Thanks!

**Comment by charlierudolph** [comment]
Thank you very much for this @eriwen. The synchronous version saved me from making some code very complex. I'm planning to refactor and eventually use the async version but this is exactly what I needed for now.

**Comment by eriwen** [comment]
You're welcome @charlierudolph :)

**Comment by Venryx** [comment]
@charlierudolph Just wanted to mention that it is also possible to synchronously get the source-mapped stack-trace. It's not part of the API, but it's possible with some modifications. See here: https://github.com/stacktracejs/stacktrace.js/issues/188
