### ISSUE TITLE
Provide a way to set custom headers in report function

### ISSUE THREAD

**Issue by enekogb** [stacktracejs/stacktrace.js#168]
I'm using StackTrace.report to send errors to my server and i need a way to send more headers than the ones provided by StackTrace (i use Spring to protect a REST API against CSRF and i need to send a header called "X-CSRF-TOKEN").

Maybe StackTrace.report should have an "options" parameter where i could add my custom header:

`var options = { headers: { X-CSRF-TOKEN: 'xxxxxxxxxxxxxxxxxxx'}};
StackTrace.report(stackframes, url, message, options) 
`

This new parameter could be used to add more options later.

**Comment by eriwen** [comment]
This is handled by https://github.com/stacktracejs/stacktrace.js/commit/2e8dbc2b41408af5a941270b2e1e8612b5a89261 and will be released in v2.0.0 soon.
