### ISSUE TITLE
Polymer Element

### ISSUE THREAD

**Issue by eriwen** [stacktracejs/stacktrace.js#179]
Wrap stacktrace.js as a [Polymer Molecule](https://elements.polymer-project.org/browse?package=molecules) and submit to elements repo.

## Expected Behavior
To Be Designed: Probably a `<stacktrace-js report="https://someerrorservice.com/report"/>` element that listens for events of a given type with Error data, parses and enhances the Error trace and reports to given `report` attribute.

## Current Behavior
No Polymer element is defined

## Context
The goal would be to make inclusion of stacktrace.js trivial using web components. Not yet understood how many users this would benefit.

**Comment by awesomehimanshu** [comment]
Any status on this ?

**Comment by eriwen** [comment]
I don't think we'll get to this.
