### ISSUE TITLE
Switch to Yarn for dependency management

### ISSUE THREAD

**Issue by eriwen** [stacktracejs/stacktrace.js#181]
[Yarn](https://yarnpkg.com/) is faster and more deterministic for dependency management.

## Expected Behavior
- [ ] Configure dependencies using Yarn and commit lockfile.
- [ ] Update [Travis CI config](https://gist.github.com/MrRio/5071b11a1d02bae30f70ab527c5f2529)

**Comment by unilynx** [comment]
Are you sure you still need this now npm apparently has caught up with version 5 ?

**Comment by eriwen** [comment]
No I don't think so
