### ISSUE TITLE
Version bump 1.3.2

### ISSUE THREAD

**Issue by fabiomcosta** [stacktracejs/stacktrace.js#186]
Hi I'm having some issues with function name detection that doesn't happen on the newest version of `stacktrace-gps`.
The new version of `stacktrace-gps` was already updated on `package.json`, so everything is working fine with `master` for me.
What are the plans on releasing a new version?
I wish I could help with that, but I can't really... my only option is to ask you to do that.

**Comment by eriwen** [comment]
v2.0.0 is tagged with 3a7a9ee6e617cf313933570697de74a39b24fd7f

**Comment by fabiomcosta** [comment]
Nice work! Thx!
