### ISSUE TITLE
Consider changing license to MIT

### ISSUE THREAD

**Issue by eriwen** [stacktracejs/stacktrace.js#187]
The reason I originally selected the Unlicense when this project began was to maximize use of the library. However, since then I've come to learn that such a license actually _prevents_ use and contribution by some organizations because Unlicense is not an OSI approved license and is a little risky legally.

I would like to consider changing the licensing to MIT as the best, most open alternative recognized by the broader OSS community. The goal, as always, is to **maximize the applicability of the software**. 

I want to know what you think. Any such license change will affect all stacktrace.js projects, and will be effective as of the next major version, 2.0. 

Please use the 👍 and 👎 reactions or discuss below.

**Comment by webmink** [comment]
I'm not involved with the codebase but am an OSI director and am responding to being "paged" on Twitter. As it happens I recently published an article on this subject:
https://meshedinsights.com/2017/03/16/public-domain-is-not-open-source/

As you'll see, it supports your conclusion.

**Comment by steren** [comment]
See here for the official Google internal documentation about contributing to open source projects: https://opensource.google.com/docs/patching/#stuff-you-cant-do

As you see, googlers are not able to contribute easily to projects under public domain license.

I support your proposal to change the license if this library.

**Comment by oliversalzburg** [comment]
I am very much in favor of MIT. Your reasoning is spot-on.

**Comment by eriwen** [comment]
Let it be written: c76dd7bb985f1f19d3f306fdfa2f54b8dbdb495a
