### ISSUE TITLE
Bower package error 2.0.0 with stacktrace-with-promises-and-json-polyfills.js (not minified version)

### ISSUE THREAD

**Issue by ndesorden** [stacktracejs/stacktrace.js#205]
The not minified version downloaded with bower has issues, for example custom headers doesnt work with report function.

In fact this version has uglified code:

With bower:
stacktrace-with-promises-and-json-polyfills.js -> **47kb** 
stacktrace-with-promises-and-json-polyfills.min.js -> 48Kb

With npm:
stacktrace-with-promises-and-json-polyfills.js -> 475kb 
stacktrace-with-promises-and-json-polyfills.min.js -> 48Kb

Please, update file in https://github.com/stacktracejs/stacktrace.js/archive/v2.0.0.tar.gz

**Comment by niftylettuce** [comment]
Can we get more maintainers on this project?

**Comment by eriwen** [comment]
This should be fixed now in v2.0.2. See https://github.com/stacktracejs/stacktrace.js/archive/v2.0.2.tar.gz
