### ISSUE TITLE
Arguments not getting populated in trace

### ISSUE THREAD

**Issue by mavericshubham** [stacktracejs/stacktrace.js#212]
Arguments are not getting populated in stack trace. Even by calling getArgs()method the args are received as null.

**Comment by eriwen** [comment]
Error stacks do not include arguments. This library can only provide arguments when calling `StackTrace.generateArtificially()` and even then, arguments are abbreviated. 

I'm going to close this for now, but if you have a specific example where arguments should be returned and are not, please comment.
