### ISSUE TITLE
Cert for https://www.stacktracejs.com/ expired

### ISSUE THREAD

**Issue by martin-displayr** [stacktracejs/stacktrace.js#220]
The Let's Encrypt cert for https://www.stacktracejs.com/ expired 23 ‎February ‎2020

**Comment by eriwen** [comment]
Thanks for the heads up. Looks like the renewal thing didn't work last time. Fixed now.

**Comment by Braunson** [comment]
Expired again, throws an error in Chrome. Cert expired on 6/24/2020.

**Comment by eriwen** [comment]
Thanks @Braunson. The trouble with auto-renew is fixed. Sorry about that.
