### ISSUE TITLE
Official Website Down

### ISSUE THREAD

**Issue by Kenneth-Sills** [stacktracejs/stacktrace.js#237]
The [official site](http://www.stacktracejs.com/) is down right now, looks like `ERR_NAME_NOT_RESOLVED`. Confirmed on [IsItDown](https://www.isitdownrightnow.com/) as well.

**Comment by Zireael07** [comment]
Still down a year later

**Comment by Kenneth-Sills** [comment]
If you really need it, they have a project [here](https://github.com/stacktracejs/www.stacktracejs.com) that defines it and has instructions on building locally.

But seems the maintainers haven't been around for a few years now, safe to say it's *probably* not coming back up. As a Hail Mary I'll tag @oliversalzburg, since they're the only active developer left in the owning org.

If that doesn't work, it may just be time to create a new project to do this instead. You could work off a fork of this or try to extend/augment a project like [TraceKit](https://github.com/csnover/TraceKit) to support source mapping ([they'd probably appreciate the help](https://github.com/csnover/TraceKit/issues/31)). For posterity, I think [this](https://tc39.es/source-map/) is the most up-to-date spec on source maps and how to retrieve them. There are [some projects](https://www.npmjs.com/package/source-map-js#consuming-a-source-map) that could help with consuming them without writing a custom extractor.

**Comment by oliversalzburg** [comment]
Thanks for the ping. I will check if and how I can help later. I definitely don't have any infrastructure or domain access, and never did.

**Comment by oliversalzburg** [comment]
@Kenneth-Sills I reached out to @eriwen, and he replied that he will look into it and respond here. :)

**Comment by eriwen** [comment]
All fixed now, sorry for the delay folks.

Please ping me if you see any further issues.
