### ISSUE TITLE
Combine efforts with TraceKit?

### ISSUE THREAD

**Issue by devinrhode2** [stacktracejs/stacktrace.js#45]
Might be of interest, https://github.com/occ/TraceKit
I've been doing plenty of work on the project, along with @occ

TraceKit supports IE. (to the extent possible)

When we combine efforts, we just get more collective bug fixes and features. Both projects basically do the same thing, so I think it makes sense to do this eventually.

**Comment by niemyjski** [comment]
Did anything ever come out of this?

**Comment by devinrhode2** [comment]
Not really, unfortunately. The most recent work I know of this is here:
https://github.com/devinrhode2/Shield.js

Now that we can write ES6 thanks to Babel, many things can be done
differently. iirc a key blocker for me was how to link up modules, which is
what my last commit had to do with. I'm sure we could make some great
progress pair programming sometime, if you or anyone is interested. My
skype username is the same as my github username.


-Devin <http://zerply.com/DevinRhode2>
<http://zerply.com/devinrhode2>
