### ISSUE TITLE
stacktrace.js breaks in strict mode in IE 10

### ISSUE THREAD

**Issue by fresheneesz** [stacktracejs/stacktrace.js#80]
I'm bundling stacktrace.js with my other modules using browserify, and the entrypoint function declares "use strict". I'm not sure why this is causing IE to evaluate stacktrace.js itself with strict mode (I suspect its not supposed to), but it's causing stacktrace.js to throw an exception in this case.

For some reason, the exception is being labeled as mode 'other' (instead of 'ie', even though this.mode(this.createException()) returns 'ie'), and is going through code that executes `curr = curr.caller`, which IE complains that "Accessing the 'caller' property of a function or arguments is not allowed in strict mode".

**Comment by rcorrie** [comment]
This was happening to me when I passed an `Object` instead of a `String`.
