### ISSUE TITLE
Make it clearer what is and isn't supported in IE when passing in exceptions

### ISSUE THREAD

**Issue by fresheneesz** [stacktracejs/stacktrace.js#82]
Passing in execeptions is in fact supported in IE - but they have to be exceptions that have been thrown. This is at least true in IE 10, and likely true in other versions. This should be noted in the docs.

**Comment by eriwen** [comment]
@mancioshell It is supported in IE10+ as long as the Error has a `stack` property.

**Comment by eriwen** [comment]
v1.0 api now makes this unambiguous.
