### ISSUE TITLE
Create NuGet package

### ISSUE THREAD

**Issue by eriwen** [stacktracejs/stacktrace.js#88]
https://www.nuget.org/

**Comment by thatgirlcancode** [comment]
i'm creating a nuget package, but would like to create one for the latest code. there hasn't been a release since Nov 2014. @eriwen are we close to another stable release? there seems to be no outstanding issues...

**Comment by thatgirlcancode** [comment]
The version numbering is a little off due to a nuget publishing error, but it's out there now >> https://www.nuget.org/packages/stacktrace.js/

**Comment by niemyjski** [comment]
+1 Thanks
